export interface FieldDef { key: string; label: string }

// One entry per logical "section".  assetTypes lists every DynamoDB
// assetType value that belongs to that section.
export const SECTIONS: { title: string; assetTypes: string[]; fields: FieldDef[] }[] = [
  {
    title: 'Laptops', assetTypes: ['Laptop'],
    fields: [
      { key: 'assetType',      label: 'Asset Type' },
      { key: 'manufacturer',   label: 'Asset Manufacturer' },
      { key: 'serviceTag',     label: 'Service Tag' },
      { key: 'model',          label: 'Model' },
      { key: 'partNumber',     label: 'P/N' },
      { key: 'assetOwner',     label: 'Asset Owner' },
      { key: 'assignedTo',     label: 'Assigned To' },
      { key: 'status',         label: 'Asset Status' },
      { key: 'lastOwner',      label: 'Last Owner' },
      { key: 'department',     label: 'Dept' },
      { key: 'location',       label: 'Location' },
      { key: 'assetHealth',    label: 'Asset Health' },
      { key: 'warranty',       label: 'Warranty' },
      { key: 'installDate',    label: 'Install Date' },
      { key: 'dateAdded',      label: 'Date Added/Updated' },
      { key: 'processor',      label: 'Processor' },
      { key: 'ram',            label: 'RAM' },
      { key: 'hardDisk',       label: 'Hard Disk' },
      { key: 'os',             label: 'O/S' },
      { key: 'supportVendor',  label: 'Supt Vendor' },
      { key: 'keyboard',       label: 'Keyboard' },
      { key: 'mouse',          label: 'Mouse' },
      { key: 'headphone',      label: 'HeadPhone' },
      { key: 'usbExtender',    label: 'USB Extender' },
      { key: 'containsPII',    label: 'Contains PII' },
    ],
  },
  {
    title: 'Desktops', assetTypes: ['Desktop'],
    fields: [
      { key: 'assetType',     label: 'Asset Type' },
      { key: 'manufacturer',  label: 'Asset Manufacturer' },
      { key: 'serviceTag',    label: 'Service Tag' },
      { key: 'model',         label: 'Model' },
      { key: 'partNumber',    label: 'P/N' },
      { key: 'assetOwner',    label: 'Asset Owner' },
      { key: 'assignedTo',    label: 'Assigned To' },
      { key: 'status',        label: 'Asset Status' },
      { key: 'lastOwner',     label: 'Last Owner' },
      { key: 'department',    label: 'Dept' },
      { key: 'location',      label: 'Location' },
      { key: 'assetHealth',   label: 'Asset Health' },
      { key: 'warranty',      label: 'Warranty' },
      { key: 'installDate',   label: 'Install Date' },
      { key: 'dateAdded',     label: 'Date Added/Updated' },
      { key: 'processor',     label: 'Processor' },
      { key: 'os',            label: 'O/S' },
      { key: 'supportVendor', label: 'Supt Vendor' },
      { key: 'configuration', label: 'Configuration' },
      { key: 'containsPII',   label: 'Contains PII' },
    ],
  },
  {
    title: 'Monitors', assetTypes: ['Monitor'],
    fields: [
      { key: 'assetType',     label: 'Asset Type' },
      { key: 'manufacturer',  label: 'Asset Manufacturer' },
      { key: 'serviceTag',    label: 'Service Tag' },
      { key: 'model',         label: 'Model' },
      { key: 'partNumber',    label: 'P/N' },
      { key: 'assetOwner',    label: 'Asset Owner' },
      { key: 'assignedTo',    label: 'Assigned To' },
      { key: 'status',        label: 'Asset Status' },
      { key: 'department',    label: 'Dept' },
      { key: 'location',      label: 'Location' },
      { key: 'assetHealth',   label: 'Asset Health' },
      { key: 'warranty',      label: 'Warranty' },
      { key: 'installDate',   label: 'Install Date' },
      { key: 'dateAdded',     label: 'Date Added/Updated' },
      { key: 'supportVendor', label: 'Supt Vendor' },
      { key: 'containsPII',   label: 'Contains PII' },
    ],
  },
  {
    title: 'Accessories',
    assetTypes: ['Keyboard', 'Mouse', 'Headphone', 'USB Extender', 'Accessory'],
    fields: [
      { key: 'assetType',     label: 'Asset Type' },
      { key: 'manufacturer',  label: 'Asset Manufacturer' },
      { key: 'model',         label: 'Model' },
      { key: 'partNumber',    label: 'P/N' },
      { key: 'assetOwner',    label: 'Asset Owner' },
      { key: 'assignedTo',    label: 'Assigned To' },
      { key: 'status',        label: 'Asset Status' },
      { key: 'department',    label: 'Dept' },
      { key: 'location',      label: 'Location' },
      { key: 'warranty',      label: 'Warranty' },
      { key: 'installDate',   label: 'Install Date' },
      { key: 'dateAdded',     label: 'Date Added/Updated' },
      { key: 'supportVendor', label: 'Supt Vendor' },
      { key: 'linkedDevice',  label: 'Linked Device Tag' },
      { key: 'containsPII',   label: 'Contains PII' },
    ],
  },
  {
    title: 'Networking',
    assetTypes: ['Switch', 'Router', 'Firewall', 'Access Point', 'Networking'],
    fields: [
      { key: 'assetType',     label: 'Asset Type' },
      { key: 'deviceId',      label: 'Asset Id' },
      { key: 'macId',         label: 'MAC ID' },
      { key: 'assetOwner',    label: 'Asset Owner' },
      { key: 'location',      label: 'Location' },
      { key: 'model',         label: 'Model' },
      { key: 'serialNumber',  label: 'S/N' },
      { key: 'partNumber',    label: 'P/N' },
      { key: 'warranty',      label: 'Warranty' },
      { key: 'installDate',   label: 'Install Date' },
      { key: 'os',            label: 'O/S' },
      { key: 'supportVendor', label: 'Supt Vendor' },
      { key: 'department',    label: 'Dept' },
      { key: 'configuration', label: 'Configuration' },
      { key: 'containsPII',   label: 'Contains PII' },
      { key: 'dateAdded',     label: 'Date Added/Updated' },
    ],
  },
  {
    title: 'Cloud Asset Register', assetTypes: ['Cloud'],
    fields: [
      { key: 'assetName',   label: 'Asset' },
      { key: 'assetType',   label: 'Asset Type' },
      { key: 'assetValue',  label: 'Asset Value' },
      { key: 'assetOwner',  label: 'Asset Owner' },
      { key: 'location',    label: 'Asset Location' },
      { key: 'containsPII', label: 'Contains PII Data' },
      { key: 'region',      label: 'Asset Region' },
      { key: 'dateAdded',   label: 'Date Added/Updated' },
    ],
  },
  {
    title: 'Infodesk Applications', assetTypes: ['Infodesk Application'],
    fields: [
      { key: 'assetName',   label: 'Asset' },
      { key: 'assetType',   label: 'Asset Type' },
      { key: 'assetValue',  label: 'Asset Value' },
      { key: 'assetOwner',  label: 'Asset Owner' },
      { key: 'location',    label: 'Asset Location' },
      { key: 'containsPII', label: 'Contains PII Data' },
      { key: 'dateAdded',   label: 'Date Added/Updated' },
    ],
  },
  {
    title: 'Third Party Software', assetTypes: ['Third Party Software'],
    fields: [
      { key: 'assetName',   label: 'Asset' },
      { key: 'assetType',   label: 'Asset Type' },
      { key: 'assetValue',  label: 'Asset Value' },
      { key: 'assetOwner',  label: 'Asset Owner' },
      { key: 'location',    label: 'Asset Location' },
      { key: 'containsPII', label: 'Contains PII Data' },
      { key: 'dateAdded',   label: 'Date Added/Updated' },
      { key: 'cveAlert',    label: 'CVE Alert' },
      { key: 'setup',       label: 'Setup' },
      { key: 'billingApi',  label: 'Billing API' },
    ],
  },
  {
    title: 'UPS', assetTypes: ['UPS'],
    fields: [
      { key: 'assetType',     label: 'Asset Type' },
      { key: 'deviceId',      label: 'Device Id' },
      { key: 'location',      label: 'Location' },
      { key: 'model',         label: 'Model' },
      { key: 'warranty',      label: 'Warranty' },
      { key: 'installDate',   label: 'Install Date' },
      { key: 'supportVendor', label: 'Supt Vendor' },
      { key: 'department',    label: 'Dept' },
      { key: 'assetOwner',    label: 'Asset Owner' },
      { key: 'containsPII',   label: 'Contains PII' },
      { key: 'dateAdded',     label: 'Date Added/Updated' },
    ],
  },
  {
    title: 'Mobile Phones', assetTypes: ['Mobile Phone'],
    fields: [
      { key: 'assetType',     label: 'Asset Type' },
      { key: 'deviceId',      label: 'Device Id' },
      { key: 'location',      label: 'Location' },
      { key: 'model',         label: 'Model' },
      { key: 'partNumber',    label: 'P/N' },
      { key: 'warranty',      label: 'Warranty' },
      { key: 'supportVendor', label: 'Supt Vendor' },
      { key: 'department',    label: 'Dept' },
      { key: 'assetOwner',    label: 'Asset Owner' },
      { key: 'containsPII',   label: 'Contains PII' },
      { key: 'dateAdded',     label: 'Date Added/Updated' },
    ],
  },
  {
    title: 'Scanners & Printers', assetTypes: ['Scanner', 'Printer'],
    fields: [
      { key: 'assetType',     label: 'Asset Type' },
      { key: 'deviceId',      label: 'Device Id' },
      { key: 'location',      label: 'Location' },
      { key: 'model',         label: 'Model' },
      { key: 'serviceTag',    label: 'Service Tag' },
      { key: 'partNumber',    label: 'P/N' },
      { key: 'warranty',      label: 'Warranty' },
      { key: 'supportVendor', label: 'Supt Vendor' },
      { key: 'department',    label: 'Dept' },
      { key: 'description',   label: 'Description' },
      { key: 'assetOwner',    label: 'Asset Owner' },
      { key: 'containsPII',   label: 'Contains PII' },
      { key: 'dateAdded',     label: 'Date Added/Updated' },
    ],
  },
  {
    title: 'Admin Cameras & DVR', assetTypes: ['Camera', 'DVR'],
    fields: [
      { key: 'assetType',     label: 'Asset Type' },
      { key: 'location',      label: 'Location' },
      { key: 'invoiceNo',     label: 'Invoice No' },
      { key: 'warranty',      label: 'Warranty' },
      { key: 'installDate',   label: 'Install Date' },
      { key: 'supportVendor', label: 'Supt Vendor' },
      { key: 'department',    label: 'Dept' },
      { key: 'assetOwner',    label: 'Asset Owner' },
      { key: 'containsPII',   label: 'Contains PII' },
      { key: 'dateAdded',     label: 'Date Added/Updated' },
    ],
  },
  {
    title: 'Gate Pass', assetTypes: ['GatePass'],
    fields: [
      { key: 'gatePassNo',         label: 'Gate Pass No' },
      { key: 'date',               label: 'Date' },
      { key: 'passType',           label: 'Pass Type' },
      { key: 'issuedTo',           label: 'Issued To' },
      { key: 'person',             label: 'Person' },
      { key: 'deptHead',           label: 'Dept Head' },
      { key: 'securityGuard',      label: 'Security Guard' },
      { key: 'receiverName',       label: 'Receiver Name' },
      { key: 'assetItems',         label: 'Asset Items' },
      { key: 'expectedReturnDate', label: 'Expected Return Date' },
      { key: 'actualReturnDate',   label: 'Actual Return Date' },
      { key: 'status',             label: 'Status' },
      { key: 'remarks',            label: 'Remarks' },
    ],
  },
  {
    title: 'Infodesk Leavers', assetTypes: ['Leaver'],
    fields: [
      { key: 'employeeName',        label: 'Employee Name' },
      { key: 'dateOfLeaving',       label: 'Date of Leaving' },
      { key: 'department',          label: 'Department' },
      { key: 'lineManager',         label: 'Line Manager' },
      { key: 'emailGroups',         label: 'Email Groups' },
      { key: 'infodeskQaDev',       label: 'Infodesk QA/Dev' },
      { key: 'infodeskProd',        label: 'Infodesk Prod' },
      { key: 'jiraWiki',            label: 'Jira & Wiki' },
      { key: 'msOffice',            label: 'MS Office' },
      { key: 'mongoAccess',         label: 'Mongo Access' },
      { key: 'azureInfodesk',       label: 'Azure Infodesk' },
      { key: 'azureWnInfodesk',     label: 'Azure WN Infodesk' },
      { key: 'vpn',                 label: 'VPN' },
      { key: 'wnVpn',               label: 'WN VPN' },
      { key: 'azureDevops',         label: 'Azure DevOps' },
      { key: 'infoAdmin',           label: 'Info Admin' },
      { key: 'zabbix',              label: 'Zabbix' },
      { key: 'github',              label: 'GitHub' },
      { key: 'infodeskPortal',      label: 'Infodesk Portal' },
      { key: 'salesforce',          label: 'Salesforce' },
      { key: 'hwInventoryLocation', label: 'HW Inventory Location' },
      { key: 'hwHandedOver',        label: 'HW Handed Over' },
      { key: 'itPeerReview',        label: 'IT Peer Review' },
      { key: 'reportingManager',    label: 'Reporting Manager' },
      { key: 'confirmationAudit',   label: 'Confirmation Audit' },
      { key: 'overallStatus',       label: 'Overall Status' },
    ],
  },
];

/** Find the section config for a given assetType */
export function getSectionByType(assetType: string) {
  return SECTIONS.find(s => s.assetTypes.includes(assetType));
}

/** Build a label→key map (case-insensitive) for a section */
export function labelKeyMap(fields: FieldDef[]): Map<string, string> {
  const m = new Map<string, string>();
  for (const f of fields) m.set(f.label.toLowerCase(), f.key);
  return m;
}
